# Generated by Django 4.2.17 on 2024-12-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_remove_comment_author_name_comment_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="song_urls",
            field=models.TextField(blank=True, null=True),
        ),
    ]
